plugins {
    id 'java'
}

group = project.maven_group
version = project.version

repositories {
    mavenCentral()
}

dependencies {
    implementation "net.minestom:minestom:${project.minestom}"

    implementation "dev.hollowcube:polar:${project.polar}"

    implementation "it.unimi.dsi:fastutil:${project.fastutil}"

    implementation "org.slf4j:slf4j-api:${project.slf4j}"
    implementation "org.slf4j:slf4j-simple:${project.slf4j}"

    implementation "org.xerial:sqlite-jdbc:${project.sqlite}"
}